version: 2
jobs:
  build:
    docker:
      - image: projectstorm/react-diagrams-ci

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # test building project
      - run: yarn run prepublishOnly

      # test building storybook
      - run: yarn run storybook:build

      # test e2e tests and jest snapshots
      - run: yarn run test:ci